version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: chat-app:blue
    restart: always
    ports:
      - 8080:8080
    environment:
      - REDIS_URL=redis://redis:6379
    networks:
      - simple-chat
    depends_on:
      - redis

  redis:
    image: redis:7.2-alpine3.18
    restart: always
    # command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - 6379:6379
    # volumes:
    #   - ./data/redis:/data
    networks:
      - simple-chat

networks:
  simple-chat:
